### ISSUE TITLE
RN的Button有问题？

### ISSUE THREAD

**Issue by fandych** [areslabs/alita#78]
当使用Button时， 编译正常， 在小程序端运行时报错;
```typescript
import React from 'react';
import {View, Text, Button, TouchableOpacity} from 'react-native';
import {history} from '@areslabs/router';

const MainPage: React.FC<{}> = ({}) => {
    return (
        <View>
            <Text>Hello World</Text>
            <View>
                <TouchableOpacity onPress={()=>{
                    history.push("SecondPage")
                }}>
                    <Text>Click Me</Text>
                </TouchableOpacity>
                <Button
                    title="Click Me"
                    onPress={() => {
                        history.push("SecondPage")
                    }}
                />
            </View>
        </View>
    );
}

export default MainPage;

```

异常：
```
VM2318:1 TypeError: inst.render is not a function
    at updateClassComponent (index.js:1888)
    at render (index.js:1303)
    at renderPage (index.js:2451)
    at index.js:2951
console.error @ VM2318:1
render @ index.js:1311
renderPage @ index.js:2451
(anonymous) @ index.js:2951
Promise.then (async)
WxNormalComp.o.methods.onLoad @ index.js:2950
(anonymous) @ VM2324 WAService.js:2
p.__callPageLifeTime__ @ VM2324 WAService.js:2
jt @ VM2324 WAService.js:2
(anonymous) @ VM2324 WAService.js:2
Mt @ VM2324 WAService.js:2
(anonymous) @ VM2324 WAService.js:2
(anonymous) @ VM2324 WAService.js:2
i.emit @ VM2324 WAService.js:2
emit @ VM2324 WAService.js:2
(anonymous) @ VM2324 WAService.js:2
i.emit @ VM2324 WAService.js:2
emit @ VM2324 WAService.js:2
(anonymous) @ VM2324 WAService.js:2
(anonymous) @ VM2324 WAService.js:2
n @ VM2322 asdebug.js:1
(anonymous) @ VM2322 asdebug.js:1
(anonymous) @ VM2322 asdebug.js:1
_ws.onmessage @ VM2322 asdebug.js:1
VM2318:1 (in promise) MiniProgramError
inst.getWxInst is not a function
TypeError: inst.getWxInst is not a function
    at Ge.<anonymous> (http://127.0.0.1:32560/appservice/_rn_.js:3984:29)
    at Ge.<anonymous> (http://127.0.0.1:32560/appservice/__dev__/WAService.js:2:1897073)
    at commitWork (http://127.0.0.1:32560/appservice/_rn_.js:3942:15)
    at renderPage (http://127.0.0.1:32560/appservice/_rn_.js:3898:3)
    at http://127.0.0.1:32560/appservice/_rn_.js:4390:9
```

**Comment by canfoo** [comment]
用的是哪个版本？

**Comment by fandych** [comment]
> 用的是哪个版本？

应该是最新的吧，最近才发现alita这个东西，在研究

**Comment by canfoo** [comment]
我大概知道什么原因，你这个是页面入口的组件吧，你把组件改成class声明，不要用functions声明，即试试这样：
```
export default class MainPage extends Component {

	render() {
		return (
			<View>
				<Text>Hello World</Text>
				<View>
					<TouchableOpacity onPress={()=>{
						history.push("SecondPage")
					}}>
						<Text>Click Me</Text>
					</TouchableOpacity>
					<Button
						title="Click Me"
						onPress={() => {
							history.push("SecondPage")
						}}
					/>
				</View>
			</View>
		)
	}

}
```

**Comment by fandych** [comment]
多谢， class声明可以正常使用
