### ISSUE TITLE
例子运行失败

### ISSUE THREAD

**Issue by houta-higuchi** [areslabs/alita#82]
运行alita --dev 后，生成小程序，微信开发者工具打开后报错  
```
页面【npm/@areslabs/wx-react-native/wxComponents/WXFlatList/index]错误:
 Error: module "npm/@areslabs/wx-react-native/wxComponents/WXFlatList/index.js" is not defined
    at require (VM40 WAService.js:2)
    at <anonymous>:90:9
    at doWhenAllScriptLoaded (appservice?t=1607136085637:2593)
    at HTMLScriptElement.scriptLoaded (appservice?t=1607136085637:2613)
    at HTMLScriptElement.script.onload (appservice?t=1607136085637:2621)
```

**Comment by guo-haozhong** [comment]
The same error to me.But no people slove it?

**Comment by ZhaoZhongYi** [comment]
您执行alita可以转化成功吗？有遇到过下面的报错吗
app@bogon HelloWorldRN % alita
配置文件路径： /Users/app/Downloads/HelloWorldRN/alita.config.js
入口文件：/Users/app/Downloads/HelloWorldRN/src/index.js
输出目录: /Users/app/Downloads/HelloWorldRN/wx-dist
开始处理：/src/index.js ...
处理完成：/src/index.js
./src/index.js
Module build failed (from ./node_modules/@areslabs/alita-core/node_modules/babel-loader/lib/index.js):
TypeError: /Users/app/Downloads/HelloWorldRN/src/index.js: pass.get(...) is not a function
    at Object.post (/Users/app/Downloads/HelloWorldRN/node_modules/@areslabs/babel-plugin-alitamisc/dist/index.js:101:47)
    at buildElementCall (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/helper-builder-react-jsx/lib/index.js:167:12)
    at PluginPass.exit (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/helper-builder-react-jsx/lib/index.js:53:24)
    at newFn (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/path/context.js:109:8)
    at TraversalContext.visitQueue (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:105:16)
    at TraversalContext.visitMultiple (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:74:17)
    at TraversalContext.visit (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:131:19)
    at traverseNode (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
    at NodePath.visit (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/path/context.js:107:52)
    at TraversalContext.visitQueue (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:105:16)
    at TraversalContext.visitMultiple (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:74:17)
    at TraversalContext.visit (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:131:19)
    at traverseNode (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/traverse-node.js:24:17)

**Comment by swdenglian** [comment]
您好，您的邮件我已经收到。----------------------------姓名：邓理安联系QQ：896291593

**Comment by yuxizhe** [comment]
Any update?

**Comment by swdenglian** [comment]
您好，您的邮件我已经收到。----------------------------姓名：邓理安联系QQ：896291593

**Comment by Jeijie** [comment]
我新建一个react native 工程，执行alita --dev转化，也是报这个错，有人知道怎么解决吗
