### ISSUE TITLE
执行alita转化失败

### ISSUE THREAD

**Issue by ZhaoZhongYi** [areslabs/alita#86]
app@bogon HelloWorldRN % alita
配置文件路径： /Users/app/Downloads/HelloWorldRN/alita.config.js
入口文件：/Users/app/Downloads/HelloWorldRN/src/index.js
输出目录: /Users/app/Downloads/HelloWorldRN/wx-dist
开始处理：/src/index.js ...
处理完成：/src/index.js
./src/index.js
Module build failed (from ./node_modules/@areslabs/alita-core/node_modules/babel-loader/lib/index.js):
TypeError: /Users/app/Downloads/HelloWorldRN/src/index.js: pass.get(...) is not a function
    at Object.post (/Users/app/Downloads/HelloWorldRN/node_modules/@areslabs/babel-plugin-alitamisc/dist/index.js:101:47)
    at buildElementCall (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/helper-builder-react-jsx/lib/index.js:167:12)
    at PluginPass.exit (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/helper-builder-react-jsx/lib/index.js:53:24)
    at newFn (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/path/context.js:109:8)
    at TraversalContext.visitQueue (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:105:16)
    at TraversalContext.visitMultiple (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:74:17)
    at TraversalContext.visit (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:131:19)
    at traverseNode (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/traverse-node.js:24:17)
    at NodePath.visit (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/path/context.js:107:52)
    at TraversalContext.visitQueue (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:105:16)
    at TraversalContext.visitMultiple (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:74:17)
    at TraversalContext.visit (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/context.js:131:19)
    at traverseNode (/Users/app/Downloads/HelloWorldRN/node_modules/@babel/traverse/lib/traverse-node.js:24:17)

**Comment by swdenglian** [comment]
您好，您的邮件我已经收到。----------------------------姓名：邓理安联系QQ：896291593

**Comment by ZhaoZhongYi** [comment]
您好 这个qq无法添加 需要输入问题：“我的手机号码是多少”


绿山墙的安妮つ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "areslabs/alita"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [areslabs/alita] 执行alita转化失败 (Issue #86)





 您好，您的邮件我已经收到。----------------------------姓名：邓理安联系QQ：896291593

**Comment by swdenglian** [comment]
不好意思，我不知道是为什么主动触发了我qq邮箱的回复= = 。我没有关注该库了
